server:
  port: 8001
  servlet:
    context-path: /sell
girl:
    cupSize: B
    age: 18
wechat:
#  myAppId: wxe0ce3eb470a3e06a
#  myAppSecret: b7411b113cc0ddbb7b5c8883db86f432
  myAppId: wxd898fcb01713c658

  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /sell/h5.p12

  notifyUrl: http://jiahanglee.natapp1.cc/sell/pay/notify